/** @deprecated Import from agent-tool-zod.ts — kept for backward-compatible imports. */
export {
  assertRestaurantIdMatches,
  FinalizeOrderRequestSchema,
  FinalizeOrderResponseSchema,
  GetRestaurantInfoPostBodySchema,
  GetRestaurantInfoQuerySchema,
  GetRestaurantInfoResponseSchema,
  GetCallerHistoryRequestSchema,
  GetCallerHistoryResponseSchema,
  GetOrderStatusRequestSchema,
  GetOrderStatusResponseSchema,
  formatZodValidationError,
  GetMenuPostBodySchema,
  GetMenuQuerySchema,
  GetMenuResponseSchema,
  parseAgentToolRequest,
  parseAgentToolResponse,
  SyncDraftOrderRequestSchema,
  SyncDraftOrderResponseSchema,
  SubmitReservationRequestSchema,
  SubmitReservationResponseSchema,
  type AgentToolErrorBody,
  type AgentToolIssue,
  type ParseResult,
} from "./agent-tool-zod.ts";
